=== PartnerofKelvaro/4850Lab8/data/schema/classSchedule.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    
    
    

    <xs:simpleType name="Ttime">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-2][0-9][0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="HourMinuteTime" id="time">
        <xs:restriction base="xs:time">
            <xs:whiteSpace value="collapse" fixed="true"/>
        </xs:restriction>
    </xs:simpleType>

    
    <xs:simpleType name="TcourseID">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-4][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Tweekday">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    
    
    
    
    <xs:element name="schedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="courses" type="Tcourses" maxOccurs="3"/>
                <xs:element name="days" type="Tdays" maxOccurs="3"/>
                <xs:element name="timeslots" type="Ttimeslots" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="Ttimeslots">
        <xs:sequence>
            <xs:element name="timeslot" type="Ttimeslot" maxOccurs="9"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Ttimeslot">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="time" type="HourMinuteTime" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="Tdays">
        <xs:sequence>
            <xs:element name="day" type="Tday" maxOccurs="6"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:complexType name="Tday">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="daySchedule" type="Tweekday" use="required"/>
    </xs:complexType>
    
    
    
    
    
    <xs:complexType name="Tcourses">
        <xs:sequence>
            <xs:element name="course" type="Tcourse" maxOccurs="6"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Tcourse">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="courseID" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    <xs:complexType name="Tbooking">
        <xs:attribute name="courseName" type="TcourseID" use="required"/>
        <xs:attribute name="weekDay" type="Tweekday" use="required"/>
        <xs:attribute name="startTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="endTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="instructor" type="xs:string" use="required"/>
        <xs:attribute name="classActivity" type="xs:string" use="required"/>
        <xs:attribute name="classLocation" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
    
</xs:schema>

=== PartnerofKelvaro/4850Lab8/data/schema/master.xml
<?xml version="1.0" encoding="UTF-8"?>



<!-- This is the facet structure for all the courses we want displayed -->
<schedule
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="classSchedule.xsd">
    <courses>
        <course courseID="4620">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30:00" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4620" weekDay="Tuesday" startTime="03:30:00" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </course>
        <course courseID="4650">
            <booking courseName="4650" weekDay="Monday" startTime="04:30:00" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30:00" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Tuesday" startTime="01:30:00" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
        </course>
        <course courseID="4660">
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30:00" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4660" weekDay="Friday" startTime="08:30:00" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </course>
        <course courseID="4770">
            <booking courseName="4770" weekDay="Monday" startTime="01:30:00" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
        </course>
        <course courseID="4850">
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30:00" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30:00" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </course>
        <course courseID="4910">
            <booking courseName="4910" weekDay="Monday" startTime="03:30:00" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4910" weekDay="Thursday" startTime="09:30:00" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking courseName="4910" weekDay="Thursday" startTime="01:30:00" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </course>
    </courses>

    <days>
        <day daySchedule="Monday">
            <booking courseName="4770" weekDay="Monday" startTime="01:30:00" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseName="4910" weekDay="Monday" startTime="03:30:00" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Monday" startTime="04:30:00" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </day>
        <day daySchedule="Tuesday">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30:00" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30:00" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Tuesday" startTime="01:30:00" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4620" weekDay="Tuesday" startTime="03:30:00" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </day>
        <day daySchedule="Wednesday">
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30:00" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30:00" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </day>
        <day daySchedule="Thursday">
            <booking courseName="4910" weekDay="Thursday" startTime="09:30:00" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30:00" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
            <booking courseName="4910" weekDay="Thursday" startTime="01:30:00" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </day>
        <day daySchedule="Friday">
            <booking courseName="4660" weekDay="Friday" startTime="08:30:00" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </day>
    </days>

    <timeslots>
        <timeslot time="08:30:00">
            <booking courseName="4660" weekDay="Friday" startTime="08:30:00" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </timeslot>
        <timeslot time="09:30:00">
            <booking courseName="4910" weekDay="Thursday" startTime="09:30:00" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
        </timeslot>
        <timeslot time="10:30:00">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30:00" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30:00" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30:00" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </timeslot>
        <timeslot time="11:30:00">
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30:00" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30:00" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </timeslot>
        <timeslot time="01:30:00">
            <booking courseName="4770" weekDay="Monday" startTime="01:30:00" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseName="4650" weekDay="Tuesday" startTime="01:30:00" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4910" weekDay="Thursday" startTime="01:30:00" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </timeslot>
        <timeslot time="03:30:00">
            <booking courseName="4910" weekDay="Monday" startTime="03:30:00" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4620" weekDay="Tuesday" startTime="03:30:00" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </timeslot>
        <timeslot time="04:30:00">
            <booking courseName="4650" weekDay="Monday" startTime="04:30:00" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </timeslot>
            
    </timeslots>
</schedule>
